imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  apsis_one.module.install:
    class: 'Apsis\One\Module\Install'
    arguments:
      - '@apsis_one.module.configuration.configs'

  apsis_one.module.uninstall:
    class: 'Apsis\One\Module\Uninstall'
    arguments:
      - '@apsis_one.module.configuration.configs'

  apsis_one.module.configuration:
    class: 'Apsis\One\Module\Configuration'
    arguments:
      - '@apsis_one.module.configuration.configs'