services:
  _defaults:
    public: true

  apsis_one.abandoned-cart.schema:
    class: 'Apsis\One\Model\AbandonedCart\Schema\Cart'

  apsis_one.abandoned-cart-item.schema:
    class: 'Apsis\One\Model\AbandonedCart\Schema\CartItem'

  apsis_one.abandoned-cart.container:
    class: 'Apsis\One\Model\AbandonedCart\DataProvider'
    arguments:
      - '@apsis_one.helper.module'