services:
  _defaults:
    public: true

  apsis_one.helper.logger:
    class: 'Apsis\One\Helper\LoggerHelper'

  apsis_one.helper.module:
    class: 'Apsis\One\Helper\ModuleHelper'

  apsis_one.helper.data:
    class: 'Apsis\One\Helper\DataHelper'

  apsis_one.helper.date:
    class: 'Apsis\One\Helper\DateHelper'

  apsis_one.helper.entity:
    class: 'Apsis\One\Helper\EntityHelper'
