# BEGIN: Module Config Route
admin_apsis_module_config:
  path: /apsis_module/config
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ModuleConfigController::indexAction'
    _legacy_controller: ApsisOneModuleConfigController
    _legacy_link: ApsisOneModuleConfigController
# END: Module Config Route

# BEGIN: Profile Routes
admin_apsis_profile_index:
  path: /apsis_profile/list
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::indexAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController

admin_apsis_profile_search:
  path: /apsis_profile/list
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController::searchProfile
    gridDefinitionFactoryServiceId: apsis_one.grid.definition.factory.profile_grid_definition_factory
    redirectRoute: admin_apsis_profile_index

admin_apsis_profile_export:
  path: /apsis_profile/export
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::exportAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController::exportProfile

admin_apsis_profile_reset:
  path: /apsis_profile/reset
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::resetAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController::resetProfile

admin_apsis_profile_delete:
  path: /apsis_profile/delete
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::deleteAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController::deleteProfile

admin_apsis_profile_reset_bulk:
  path: /apsis_profile/reset-bulk
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::resetBulkAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController::bulkResetProfile

admin_apsis_profile_delete_bulk:
  path: /apsis_profile/delete-bulk
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::deleteBulkAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController::bulkDeleteProfile

# END: Profile routes

# BEGIN: Event Routes
admin_apsis_event_index:
  path: /apsis_event/list
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::indexAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController

admin_apsis_event_search:
  path: /apsis_event/list
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController::searchEvent
    gridDefinitionFactoryServiceId: apsis_one.grid.definition.factory.event_grid_definition_factory
    redirectRoute: admin_apsis_event_index

admin_apsis_event_export:
  path: /apsis_event/export
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::exportAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController::exportEvent

admin_apsis_event_reset:
  path: /apsis_event/reset
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::resetAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController::resetEvent

admin_apsis_event_delete:
  path: /apsis_event/delete
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::deleteAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController::deleteEvent

admin_apsis_event_reset_bulk:
  path: /apsis_event/reset-bulk
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::resetBulkAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController::bulkResetEvent

admin_apsis_event_delete_bulk:
  path: /apsis_event/delete-bulk
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::deleteBulkAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController::bulkDeleteEvent

# END: Event Routes

# BEGIN: AbandonedCart Routes
admin_apsis_abandonedcart_index:
  path: /apsis_abandonedcart/list
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::indexAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController

admin_apsis_abandonedcart_search:
  path: /apsis_abandonedcart/list
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController::searchAbandonedcart
    gridDefinitionFactoryServiceId: apsis_one.grid.definition.factory.abandonedcart_grid_definition_factory
    redirectRoute: admin_apsis_abandonedcart_index

admin_apsis_abandonedcart_export:
  path: /apsis_abandonedcart/export
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::exportAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController::exportAbandonedcart

admin_apsis_abandonedcart_reset:
  path: /apsis_abandonedcart/reset
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::resetAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController::resetAbandonedcart

admin_apsis_abandonedcart_delete:
  path: /apsis_abandonedcart/delete
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::deleteAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController::deleteAbandonedcart

admin_apsis_abandonedcart_reset_bulk:
  path: /apsis_abandonedcart/reset-bulk
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::resetBulkAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController::bulkResetAbandonedcart

admin_apsis_abandonedcart_delete_bulk:
  path: /apsis_abandonedcart/delete-bulk
  methods: [POST]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::deleteBulkAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController::bulkDeleteAbandonedcart

# END: AbandonedCart Routes
