# BEGIN: Profile Routes
admin_apsis_profile_index:
  path: /apsis_profile/list
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::indexAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController

admin_apsis_profile_search:
  path: /
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Common:searchGrid'
    gridDefinitionFactoryServiceId: apsis_one.grid.definition.factory.profile_grid_definition_factory
    redirectRoute: admin_apsis_profile_index
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController

admin_apsis_profile_export:
  path: /apsis_profile/export
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::exportAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController

admin_apsis_profile_reset:
  path: /apsis_profile/reset
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::resetAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController

admin_apsis_profile_delete:
  path: /apsis_profile/delete
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\ProfileController::deleteAction'
    _legacy_controller: ApsisOneProfileController
    _legacy_link: ApsisOneProfileController

# END: Profile routes

# BEGIN: Event Routes
admin_apsis_event_index:
  path: /apsis_event/list
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::indexAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController

admin_apsis_event_search:
  path: /
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Common:searchGrid'
    gridDefinitionFactoryServiceId: apsis_one.grid.definition.factory.event_grid_definition_factory
    redirectRoute: admin_apsis_event_index
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController

admin_apsis_event_export:
  path: /apsis_event/export
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::exportAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController

admin_apsis_event_reset:
  path: /apsis_event/reset
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::resetAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController

admin_apsis_event_delete:
  path: /apsis_event/delete
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\EventController::deleteAction'
    _legacy_controller: ApsisOneEventController
    _legacy_link: ApsisOneEventController

# END: Event Routes

# BEGIN: AbandonedCart Routes
admin_apsis_abandonedcart_index:
  path: /apsis_abandonedcart/list
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::indexAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController

admin_apsis_abandonedcart_search:
  path: /
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Common:searchGrid'
    gridDefinitionFactoryServiceId: apsis_one.grid.definition.factory.abandonedcart_grid_definition_factory
    redirectRoute: admin_apsis_abandonedcart_index
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController

admin_apsis_abandonedcart_export:
  path: /apsis_abandonedcart/export
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::exportAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController

admin_apsis_abandonedcart_reset:
  path: /apsis_abandonedcart/reset
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::resetAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController

admin_apsis_abandonedcart_delete:
  path: /apsis_abandonedcart/delete
  methods: [GET]
  defaults:
    _controller: 'Apsis\One\Controller\Admin\AbandonedCartController::deleteAction'
    _legacy_controller: ApsisOneAbandonedCartController
    _legacy_link: ApsisOneAbandonedCartController

# END: AbandonedCart Routes