services:
  _defaults:
    public: true

  # BEGIN: Profile Grid Services
  apsis_one.form.choice_provider.profile_sync_status_provider:
    class: 'Apsis\One\Form\ChoiceProvider\ProfileSyncStatusProvider'

  apsis_one.grid.definition.factory.profile_grid_definition_factory:
    class: 'Apsis\One\Grid\Definition\Factory\ProfileGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    arguments:
      - '@apsis_one.form.choice_provider.profile_sync_status_provider'
    public: true

  apsis_one.grid.query.profile_query_builder:
    class: 'Apsis\One\Grid\Query\ProfileQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
    public: true

  apsis_one.grid.data.factory.profile_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@apsis_one.grid.query.profile_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'apsis_profile'

  apsis_one.grid.data.factory.profile_data_factory_decorator:
    class: 'Apsis\One\Grid\Data\Factory\ProfileGridDataFactoryDecorator'
    arguments:
      - '@apsis_one.grid.data.factory.profile_data_factory'
      - '@apsis_one.form.choice_provider.profile_sync_status_provider'

  apsis_one.grid.profile_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@apsis_one.grid.definition.factory.profile_grid_definition_factory'
      - '@apsis_one.grid.data.factory.profile_data_factory_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  Apsis\One\Controller\Admin\ProfileController:
    class: 'Apsis\One\Controller\Admin\ProfileController'
    arguments:
      - '@apsis_one.grid.profile_grid_factory'
      - 'admin_apsis_profile_index'

  # END: Profile Grid Services

  # BEGIN: Event Grid Services
  apsis_one.form.choice_provider.event_sync_status_provider:
    class: 'Apsis\One\Form\ChoiceProvider\EventSyncStatusProvider'

  apsis_one.form.choice_provider.event_type_provider:
    class: 'Apsis\One\Form\ChoiceProvider\EventTypeProvider'

  apsis_one.grid.definition.factory.event_grid_definition_factory:
    class: 'Apsis\One\Grid\Definition\Factory\EventGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    arguments:
      - '@apsis_one.form.choice_provider.event_sync_status_provider'
      - '@apsis_one.form.choice_provider.event_type_provider'
    public: true

  apsis_one.grid.query.event_query_builder:
    class: 'Apsis\One\Grid\Query\EventQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
    public: true

  apsis_one.grid.data.factory.event_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@apsis_one.grid.query.event_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'apsis_event'

  apsis_one.grid.data.factory.event_data_factory_decorator:
    class: 'Apsis\One\Grid\Data\Factory\EventGridDataFactoryDecorator'
    arguments:
      - '@apsis_one.grid.data.factory.event_data_factory'
      - '@apsis_one.form.choice_provider.event_sync_status_provider'
      - '@apsis_one.form.choice_provider.event_type_provider'

  apsis_one.grid.event_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@apsis_one.grid.definition.factory.event_grid_definition_factory'
      - '@apsis_one.grid.data.factory.event_data_factory_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  Apsis\One\Controller\Admin\EventController:
    class: 'Apsis\One\Controller\Admin\EventController'
    arguments:
      - '@apsis_one.grid.event_grid_factory'
      - 'admin_apsis_event_index'

  # END: Event Grid Services

  # BEGIN: AbandonedCart Grid Services
  apsis_one.grid.definition.factory.abandonedcart_grid_definition_factory:
    class: 'Apsis\One\Grid\Definition\Factory\AbandonedCartGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  apsis_one.grid.query.abandonedcart_query_builder:
    class: 'Apsis\One\Grid\Query\AbandonedCartQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
    public: true

  apsis_one.grid.data.factory.abandonedcart_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@apsis_one.grid.query.abandonedcart_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'apsis_abandoned_cart'

  apsis_one.grid.abandonedcart_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@apsis_one.grid.definition.factory.abandonedcart_grid_definition_factory'
      - '@apsis_one.grid.data.factory.abandonedcart_data_factory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  Apsis\One\Controller\Admin\AbandonedCartController:
    class: 'Apsis\One\Controller\Admin\AbandonedCartController'
    arguments:
      - '@apsis_one.grid.abandonedcart_grid_factory'
      - 'admin_apsis_abandonedcart_index'

  # END: AbandonedCart Grid Services
